# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: prt

before:
  hooks:
    - go mod tidy

builds:
  - id: prt
    main: ./cmd/prt
    binary: prt
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    include:
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
      - "^style"
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: ChrisEdwards
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/ChrisEdwards/pr-tracker"
    description: "GitHub PR Tracker - Aggregate PR status across multiple repositories"
    license: "MIT"
    dependencies:
      - name: gh
        type: recommended
    install: |
      bin.install "prt"
    test: |
      system "#{bin}/prt", "--version"
    caveats: |
      PRT requires the GitHub CLI (gh) to be installed and authenticated.

      If not already installed:
        brew install gh

      Then authenticate:
        gh auth login

      Run `prt` to start the setup wizard.

release:
  github:
    owner: ChrisEdwards
    name: pr-tracker
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
